workflows:
  dev-android:
    name: Dev android
    publishing:
      email:
        recipients:
          - mohamad.samer.abdulaziz@gmail.com
        notify:
          success: true
          failure: false
