workflows:
  dev-android:
    name: Dev android
    environment:
      flutter:
        version: stable 3.10.6
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build apk with flutter
        script: |
          flutter build apk
    publishing:
      email:
        recipients:
          - mohamad.samer.abdulaziz@gmail.com
        notify:
          success: true
          failure: false
