workflows:
  dev-android:
    name: Dev android
    environment:
      flutter:
        version: stable 3.10.6
    publishing:
      email:
        recipients:
          - mohamad.samer.abdulaziz@gmail.com
        notify:
          success: true
          failure: false
